question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data2 = [
    {"type": "multiple", "difficulty": "hard", "category": "Politics", "question": "What is centralism?",
     "correct_answer": " Concentration of power and authority in a central organization.",
     "incorrect_answers": ["Conforming to one single common political agenda.", "Remaining politically neutral.",
                           "The grey area in the spectrum of political left and right."]},
        {"type": "multiple", "difficulty": "hard", "category": "Geography",
         "question": "What national museum will you find in Cooperstown, New York?",
         "correct_answer": "National Baseball Hall of Fame",
         "incorrect_answers": ["Metropolitan Museum of Art", "National Toy Hall of Fame", "Museum of Modern Art"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "What is the name of the main character of the anime &quot;One-Punch Man&quot;?",
         "correct_answer": "Saitama", "incorrect_answers": ["Genos", "Sonic", "King"]},
        {"type": "multiple", "difficulty": "medium", "category": "Celebrities",
         "question": "Which radio personality calls himself &quot;The King of All Media&quot;?",
         "correct_answer": "Howard Stern", "incorrect_answers": ["Rush Limbaugh", "Pete Tong", "Ryan Seacrest"]},
        {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "In Diablo lore, this lesser evil spawned from one of the seven heads of Tathamet, and was known as the Maiden of Anguish.",
         "correct_answer": "Andariel", "incorrect_answers": ["Valla", "Malthael", "Kashya"]},
        {"type": "boolean", "difficulty": "medium", "category": "Geography",
         "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Which character in the &quot;Animal Crossing&quot; series uses the phrase &quot;zip zoom&quot; when talking to the player?",
         "correct_answer": "Scoot", "incorrect_answers": ["Drake", "Bill", "Mallary"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "Which of the following colors does the Zombie eyes glow in the &quot;Nuketown&quot; map in &quot;Call of Duty: Black Ops II&quot; Zombies mode?",
         "correct_answer": "Yellow and Blue",
         "incorrect_answers": ["Yellow and Red", "Red and Blue", "Blue and White"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
         "question": "Which singer provided the voice of Metroid&#039;s Mother Brain in the animated series &quot;Captain N: The Game Master&quot;?",
         "correct_answer": "Levi Stubbs", "incorrect_answers": ["Freddie Mercury", "Janet Jackson", "Joan Jett"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
         "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]
